apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaler-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-binding
subjects:
- kind: ServiceAccount
  name: scaler
roleRef:
  kind: Role
  name: scaler-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-sentinel-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: scaler
      containers:
      - name: controller
        image: blackdranzer/data-sentinel:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: watch-dir
          mountPath: /host-files
      volumes:
      - name: watch-dir
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["sh", "-c", "while true; do sleep 3600; done"]
